# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('item_type', models.CharField(default='post', max_length=30)),
                ('item_id', models.CharField(max_length=64)),
                ('is_seed_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'connecta_saved_items',
            },
        ),
    ]
