# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, default='', max_length=500)),
                ('story_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('background_color', models.CharField(blank=True, default='#1877F2', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('is_seed_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'connecta_stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
