# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('poll', 'Poll'), ('shared', 'Shared'), ('check_in', 'Check-In')], default='text', max_length=20)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('only_me', 'Only Me')], default='public', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('poll_data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_seed_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connecta_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
