# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('fake_account', 'Fake Account'), ('hate_content', 'Hate/Abusive Content'), ('scam', 'Scam'), ('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright'), ('other', 'Other')], default='spam', max_length=30)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('group', 'Group'), ('page', 'Page'), ('marketplace', 'Marketplace Listing')], default='post', max_length=30)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderator_notes', models.TextField(blank=True, default='')),
                ('is_seed_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connecta_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
