# Generated by Django 6.1.1 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(default='System Admin', max_length=150)),
                ('admin_role', models.CharField(default='super_admin', max_length=50)),
                ('action', models.CharField(max_length=150)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_seed_data', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'connecta_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_reactions', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_reports', models.IntegerField(default=0)),
                ('is_seed_data', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'connecta_daily_analytics',
                'ordering': ['-date'],
            },
        ),
    ]
