# Generated by Django 6.1.1 on 2026-09-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('memory_date', models.DateTimeField()),
                ('is_seed_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.photo')),
            ],
            options={
                'db_table': 'connecta_memories',
            },
        ),
    ]
